spring:
  application:
    name: fitapp
  profiles:
    # default senza DB;
    default: nodb

security:
  jwt:
    issuer: fitapp
    secret: ${JWT_SECRET:s3cUr3-JWT-53cr3t-84y7e5-9xPz1LmQvRtWuYj2}
    ttlMinutes: 120

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
