spring:
  application:
    name: fitapp
  profiles:
    active: nodb

---
spring:
  config:
    activate:
      on-profile: nodb

# niente Liquibase/JPA/DataSource nel profilo senza DB
spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration

security:
  jwt:
    issuer: fitapp
    secret: ${JWT_SECRET:s3cUr3-JWT-53cr3t-84y7e5-9xPz1LmQvRtWuYj2}
    ttlMinutes: 120

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

---
spring:
  config:
    activate:
      on-profile: dev

# DB (Postgres locale)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fitapp}
    username: ${SPRING_DATASOURCE_USERNAME:fitapp}
    password: ${SPRING_DATASOURCE_PASSWORD:fitapp}
    hikari:
      maximum-pool-size: 5

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

security:
  jwt:
    issuer: fitapp
    secret: ${JWT_SECRET:s3cUr3-JWT-53cr3t-84y7e5-9xPz1LmQvRtWuYj2}
    ttlMinutes: 120

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESSKEY:minio}
  secretKey: ${MINIO_SECRETKEY:minio123}
  bucket: ${MINIO_BUCKET:fitapp-media}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

logging:
  level:
    liquibase: INFO    # o DEBUG
    org.springframework.jdbc: INFO